### ISSUE TITLE
Doesn't work with Safari

### ISSUE THREAD

**Issue by nvlgzr** [honeybeeSunshine/svelte-GridTiles#2]
Hi! Cool project. :)

Thought you might like to know: Move and Resize both fail to respond when mucking about with your [REPL](https://svelte.dev/repl/b993c8f5fa9f4105aa9a246321025166?version=3.46.4). Here's a screen capture of the problem.

https://user-images.githubusercontent.com/88254481/158305593-dc27790d-2396-482d-829b-5fdc3050e148.mov

Cheers!

**Comment by honeybeeSunshine** [comment]
Hey thanks for the heads up! It's working now in Epiphany, so hopefully that means it will work in Safari too.

**Comment by nvlgzr** [comment]
Nope. Works in Chrome, but not Safari. ¯\\\_(ツ)_/¯ Unless maybe your fixes are at a different REPL URL?
